CREATE TABLE [dbo].[User]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1000, 1),
	[FIO] NVARCHAR(100) NOT NULL,
	[Phone] NVARCHAR(50) NOT NULL,
	[CountryID] INT NOT NULL,
	CONSTRAINT [FK_User_Country] FOREIGN KEY ([CountryID]) REFERENCES [Country]([ID]),
)
